[versions]
agp = "8.8.0"
aboutlibraries = "11.2.3"
biometric = "1.1.0"
checkerCompatQual = "2.5.6"
crashlytics = "3.0.2"
dynamicanimation = "1.0.0"
exifinterface = "1.3.7"
coreKtx = "1.15.0"
fragment = "1.8.5"
firebase = "33.6.0"
gms = "4.4.2"
gson = "2.11.0"
guava = "33.3.1-jre"
hiddenapibypass = "5.1"
interpolator = "1.0.0"
isoparser = "1.0.6" # DO NOT UPDATE THIS DEPENDENCY
imageLabeling= "16.0.8"
kotlin = "2.1.0"
ksp = "2.1.0-1.0.29"
kotlinxCoroutinesAndroid = "1.9.0"
kotlinxSerializationJson = "1.8.0"
ktor = "3.0.3"
languageId = "17.0.6"
osmdroidAndroid = "6.1.20"
playServicesLocation = "21.3.0"
playServicesVision = "20.1.3"
playServicesWallet = "19.4.0"
poet = "2.0.0"
mlkitVision = "16.0.0-beta1"
processPhoenix = "3.0.0"
sharetarget = "1.2.0"
paletteKtx = "1.0.0"
rust = "0.9.6"

[libraries]
checker-compat-qual = { module = "org.checkerframework:checker-compat-qual", version.ref = "checkerCompatQual" }
dynamicanimation = { module = "androidx.dynamicanimation:dynamicanimation", version.ref = "dynamicanimation" }
exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-config = { module = "com.google.firebase:firebase-config" }
firebase-crashlytics-ndk = { module = "com.google.firebase:firebase-crashlytics-ndk" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
isoparser = { module = "com.googlecode.mp4parser:isoparser", version.ref = "isoparser" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-common = { module = "org.jetbrains.kotlin:kotlin-stdlib-common", version.ref = "kotlin" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "poet" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
language-id = { module = "com.google.mlkit:language-id", version.ref = "languageId" }
osmdroid-android = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroidAndroid" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-vision = { module = "com.google.android.gms:play-services-vision", version.ref = "playServicesVision" }
play-services-wallet = { module = "com.google.android.gms:play-services-wallet", version.ref = "playServicesWallet" }
play-services-mlkit-vision = { module = "com.google.android.gms:play-services-mlkit-subject-segmentation", version.ref = "mlkitVision" }
play-services-mlkit-imageLabeling = { module = "com.google.android.gms:play-services-mlkit-image-labeling", version.ref = "imageLabeling" }
process-phoenix = { module = "com.jakewharton:process-phoenix", version.ref = "processPhoenix" }
sharetarget = { module = "androidx.sharetarget:sharetarget", version.ref = "sharetarget" }
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
interpolator = { module = "androidx.interpolator:interpolator", version.ref = "interpolator" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktor" }

[plugins]
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin" , version.ref = "aboutlibraries" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
google-services = { id = "com.google.gms.google-services", version.ref = "gms" }
triplet-play = { id = "com.github.triplet.play", version = "3.12.1" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
rust = { id = "org.mozilla.rust-android-gradle.rust-android", version.ref = "rust" }
