name: revert release stable commit

on:
    workflow_dispatch:
    push:
        branches:
            - master
        paths:
            - "buildSrc/src/main/kotlin/Version.kt"

jobs:
    build:
        name: Revert release stable commit
        if: ${{ github.event_name != 'pull_request' && success() && github.ref == 'refs/heads/master' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: 'recursive'
                token: ${{ secrets.PAT }}
                fetch-depth: 0

            -   name: setup git identity
                run: |
                    git config --global user.email "github-actions[bot]@users.noreply.github.com"
                    git config --global user.name "github-actions[bot]"

            - name: Modify Version.kt
              run: |
                  sed -i 's/isStable = true/isStable = false/' buildSrc/src/main/kotlin/Version.kt

            - name: Check and commit
              run: |
                  if [ -n "$(git status --porcelain)" ];
                  then
                      git commit -am "chore: revert release stable commit" -m "This commit was generated by a GitHub Action." -m "[skip ci]"
                      git push
                  else
                      echo "do nothing"
                  fi
